/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_events (mainwin, GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK | GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (mainwin), _("Screen test"));
  gtk_window_set_modal (GTK_WINDOW (mainwin), TRUE);
  gtk_window_set_decorated (GTK_WINDOW (mainwin), FALSE);

  g_signal_connect ((gpointer) mainwin, "realize",
                    G_CALLBACK (on_mainwin_realize),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "expose_event",
                    G_CALLBACK (on_mainwin_expose_event),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "button_press_event",
                    G_CALLBACK (on_mainwin_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwin, mainwin, "mainwin");

  return mainwin;
}

GtkWidget*
create_popup (void)
{
  GtkWidget *popup;
  GtkWidget *mode;
  GtkWidget *mode_menu;
  GSList *basic_group = NULL;
  GtkWidget *basic;
  GtkWidget *grid;
  GtkWidget *horizontal;
  GtkWidget *vertical;
  GtkWidget *blink;
  GtkWidget *text;
  GtkWidget *fg_color;
  GtkWidget *image4;
  GtkWidget *bg_color;
  GtkWidget *image5;
  GtkWidget *separator1;
  GtkWidget *exit;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  popup = gtk_menu_new ();

  mode = gtk_menu_item_new_with_mnemonic (_("Mode"));
  gtk_widget_show (mode);
  gtk_container_add (GTK_CONTAINER (popup), mode);

  mode_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mode), mode_menu);

  basic = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Basic"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (basic));
  gtk_widget_show (basic);
  gtk_container_add (GTK_CONTAINER (mode_menu), basic);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (basic), TRUE);

  grid = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Grid"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (grid));
  gtk_widget_show (grid);
  gtk_container_add (GTK_CONTAINER (mode_menu), grid);

  horizontal = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Horizontal"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (horizontal));
  gtk_widget_show (horizontal);
  gtk_container_add (GTK_CONTAINER (mode_menu), horizontal);

  vertical = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Vertical"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vertical));
  gtk_widget_show (vertical);
  gtk_container_add (GTK_CONTAINER (mode_menu), vertical);

  blink = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Blink"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (blink));
  gtk_widget_show (blink);
  gtk_container_add (GTK_CONTAINER (mode_menu), blink);

  text = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Text"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (text));
  gtk_widget_show (text);
  gtk_container_add (GTK_CONTAINER (mode_menu), text);

  fg_color = gtk_image_menu_item_new_with_mnemonic (_("Foreground Color"));
  gtk_widget_show (fg_color);
  gtk_container_add (GTK_CONTAINER (popup), fg_color);
  gtk_widget_add_accelerator (fg_color, "activate", accel_group,
                              GDK_F, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image4 = gtk_image_new_from_stock ("gtk-color-picker", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image4);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (fg_color), image4);

  bg_color = gtk_image_menu_item_new_with_mnemonic (_("Background Color"));
  gtk_widget_show (bg_color);
  gtk_container_add (GTK_CONTAINER (popup), bg_color);
  gtk_widget_add_accelerator (bg_color, "activate", accel_group,
                              GDK_B, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image5 = gtk_image_new_from_stock ("gtk-color-picker", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image5);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (bg_color), image5);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (popup), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  exit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (popup), exit);

  g_signal_connect ((gpointer) basic, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_BASIC);
  g_signal_connect ((gpointer) grid, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_GRID);
  g_signal_connect ((gpointer) horizontal, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_HORIZONTAL);
  g_signal_connect ((gpointer) vertical, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_VERTICAL);
  g_signal_connect ((gpointer) blink, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_BLINK);
  g_signal_connect ((gpointer) text, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_TEXT);
  g_signal_connect ((gpointer) fg_color, "activate",
                    G_CALLBACK (on_fg_color_activate),
                    NULL);
  g_signal_connect ((gpointer) bg_color, "activate",
                    G_CALLBACK (on_bg_color_activate),
                    NULL);
  g_signal_connect ((gpointer) exit, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup, popup, "popup");
  GLADE_HOOKUP_OBJECT (popup, mode, "mode");
  GLADE_HOOKUP_OBJECT (popup, mode_menu, "mode_menu");
  GLADE_HOOKUP_OBJECT (popup, basic, "basic");
  GLADE_HOOKUP_OBJECT (popup, grid, "grid");
  GLADE_HOOKUP_OBJECT (popup, horizontal, "horizontal");
  GLADE_HOOKUP_OBJECT (popup, vertical, "vertical");
  GLADE_HOOKUP_OBJECT (popup, blink, "blink");
  GLADE_HOOKUP_OBJECT (popup, text, "text");
  GLADE_HOOKUP_OBJECT (popup, fg_color, "fg_color");
  GLADE_HOOKUP_OBJECT (popup, image4, "image4");
  GLADE_HOOKUP_OBJECT (popup, bg_color, "bg_color");
  GLADE_HOOKUP_OBJECT (popup, image5, "image5");
  GLADE_HOOKUP_OBJECT (popup, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (popup, exit, "exit");

  gtk_menu_set_accel_group (GTK_MENU (popup), accel_group);

  return popup;
}

GtkWidget*
create_fg_color_selector (void)
{
  GtkWidget *fg_color_selector;
  GtkWidget *fg_color_ok;
  GtkWidget *fg_color_cancel;
  GtkWidget *fg_color_help;
  GtkWidget *fg_color_selection;

  fg_color_selector = gtk_color_selection_dialog_new (_("Select Foreground color"));
  gtk_window_set_modal (GTK_WINDOW (fg_color_selector), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (fg_color_selector), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (fg_color_selector), GDK_WINDOW_TYPE_HINT_DIALOG);

  fg_color_ok = GTK_COLOR_SELECTION_DIALOG (fg_color_selector)->ok_button;
  gtk_widget_show (fg_color_ok);
  GTK_WIDGET_SET_FLAGS (fg_color_ok, GTK_CAN_DEFAULT);

  fg_color_cancel = GTK_COLOR_SELECTION_DIALOG (fg_color_selector)->cancel_button;
  gtk_widget_show (fg_color_cancel);
  GTK_WIDGET_SET_FLAGS (fg_color_cancel, GTK_CAN_DEFAULT);

  fg_color_help = GTK_COLOR_SELECTION_DIALOG (fg_color_selector)->help_button;
  GTK_WIDGET_SET_FLAGS (fg_color_help, GTK_CAN_DEFAULT);

  fg_color_selection = GTK_COLOR_SELECTION_DIALOG (fg_color_selector)->colorsel;
  gtk_widget_show (fg_color_selection);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (fg_color_selection), FALSE);
  gtk_color_selection_set_has_palette (GTK_COLOR_SELECTION (fg_color_selection), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fg_color_selector, fg_color_selector, "fg_color_selector");
  GLADE_HOOKUP_OBJECT_NO_REF (fg_color_selector, fg_color_ok, "fg_color_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fg_color_selector, fg_color_cancel, "fg_color_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (fg_color_selector, fg_color_help, "fg_color_help");
  GLADE_HOOKUP_OBJECT_NO_REF (fg_color_selector, fg_color_selection, "fg_color_selection");

  return fg_color_selector;
}

GtkWidget*
create_bg_color_selector (void)
{
  GtkWidget *bg_color_selector;
  GtkWidget *bg_color_ok;
  GtkWidget *bg_color_cancel;
  GtkWidget *bg_color_help;
  GtkWidget *bg_color_selection;

  bg_color_selector = gtk_color_selection_dialog_new (_("Select Background color"));
  gtk_window_set_modal (GTK_WINDOW (bg_color_selector), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (bg_color_selector), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (bg_color_selector), GDK_WINDOW_TYPE_HINT_DIALOG);

  bg_color_ok = GTK_COLOR_SELECTION_DIALOG (bg_color_selector)->ok_button;
  gtk_widget_show (bg_color_ok);
  GTK_WIDGET_SET_FLAGS (bg_color_ok, GTK_CAN_DEFAULT);

  bg_color_cancel = GTK_COLOR_SELECTION_DIALOG (bg_color_selector)->cancel_button;
  gtk_widget_show (bg_color_cancel);
  GTK_WIDGET_SET_FLAGS (bg_color_cancel, GTK_CAN_DEFAULT);

  bg_color_help = GTK_COLOR_SELECTION_DIALOG (bg_color_selector)->help_button;
  GTK_WIDGET_SET_FLAGS (bg_color_help, GTK_CAN_DEFAULT);

  bg_color_selection = GTK_COLOR_SELECTION_DIALOG (bg_color_selector)->colorsel;
  gtk_widget_show (bg_color_selection);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (bg_color_selection), FALSE);
  gtk_color_selection_set_has_palette (GTK_COLOR_SELECTION (bg_color_selection), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bg_color_selector, bg_color_selector, "bg_color_selector");
  GLADE_HOOKUP_OBJECT_NO_REF (bg_color_selector, bg_color_ok, "bg_color_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (bg_color_selector, bg_color_cancel, "bg_color_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (bg_color_selector, bg_color_help, "bg_color_help");
  GLADE_HOOKUP_OBJECT_NO_REF (bg_color_selector, bg_color_selection, "bg_color_selection");

  return bg_color_selector;
}

