/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_events (mainwin, GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK | GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (mainwin), _("Screen test"));
  gtk_window_set_modal (GTK_WINDOW (mainwin), TRUE);
  gtk_window_set_decorated (GTK_WINDOW (mainwin), FALSE);

  g_signal_connect ((gpointer) mainwin, "realize",
                    G_CALLBACK (on_mainwin_realize),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "expose_event",
                    G_CALLBACK (on_mainwin_expose_event),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "button_press_event",
                    G_CALLBACK (on_mainwin_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwin, mainwin, "mainwin");

  return mainwin;
}

GtkWidget*
create_popup (void)
{
  GtkWidget *popup;
  GtkWidget *mode;
  GtkWidget *mode_menu;
  GSList *basic_group = NULL;
  GtkWidget *basic;
  GtkWidget *grid;
  GtkWidget *horizontal;
  GtkWidget *vertical;
  GtkWidget *blink;
  GtkWidget *text;
  GtkWidget *fg_color;
  GtkWidget *fg_color_menu;
  GSList *fg_white_group = NULL;
  GtkWidget *fg_white;
  GtkWidget *fg_red;
  GtkWidget *fg_green;
  GtkWidget *fg_blue;
  GtkWidget *fg_cyan;
  GtkWidget *fg_magenta;
  GtkWidget *fg_yellow;
  GtkWidget *fg_black;
  GtkWidget *bg_color;
  GtkWidget *bg_color_menu;
  GSList *bg_white_group = NULL;
  GtkWidget *bg_white;
  GtkWidget *bg_red;
  GtkWidget *bg_green;
  GtkWidget *bg_blue;
  GtkWidget *bg_cyan;
  GtkWidget *bg_magenta;
  GtkWidget *bg_yellow;
  GtkWidget *bg_black;
  GtkWidget *separator1;
  GtkWidget *exit;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  popup = gtk_menu_new ();

  mode = gtk_menu_item_new_with_mnemonic (_("Mode"));
  gtk_widget_show (mode);
  gtk_container_add (GTK_CONTAINER (popup), mode);

  mode_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mode), mode_menu);

  basic = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Basic"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (basic));
  gtk_widget_show (basic);
  gtk_container_add (GTK_CONTAINER (mode_menu), basic);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (basic), TRUE);

  grid = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Grid"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (grid));
  gtk_widget_show (grid);
  gtk_container_add (GTK_CONTAINER (mode_menu), grid);

  horizontal = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Horizontal"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (horizontal));
  gtk_widget_show (horizontal);
  gtk_container_add (GTK_CONTAINER (mode_menu), horizontal);

  vertical = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Vertical"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vertical));
  gtk_widget_show (vertical);
  gtk_container_add (GTK_CONTAINER (mode_menu), vertical);

  blink = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Blink"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (blink));
  gtk_widget_show (blink);
  gtk_container_add (GTK_CONTAINER (mode_menu), blink);

  text = gtk_radio_menu_item_new_with_mnemonic (basic_group, _("Text"));
  basic_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (text));
  gtk_widget_show (text);
  gtk_container_add (GTK_CONTAINER (mode_menu), text);

  fg_color = gtk_menu_item_new_with_mnemonic (_("Foreground Color"));
  gtk_widget_show (fg_color);
  gtk_container_add (GTK_CONTAINER (popup), fg_color);

  fg_color_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (fg_color), fg_color_menu);

  fg_white = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("White"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_white));
  gtk_widget_show (fg_white);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_white);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (fg_white), TRUE);

  fg_red = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Red"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_red));
  gtk_widget_show (fg_red);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_red);

  fg_green = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Green"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_green));
  gtk_widget_show (fg_green);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_green);

  fg_blue = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Blue"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_blue));
  gtk_widget_show (fg_blue);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_blue);

  fg_cyan = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Cyan"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_cyan));
  gtk_widget_show (fg_cyan);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_cyan);

  fg_magenta = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Magenta"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_magenta));
  gtk_widget_show (fg_magenta);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_magenta);

  fg_yellow = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Yellow"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_yellow));
  gtk_widget_show (fg_yellow);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_yellow);

  fg_black = gtk_radio_menu_item_new_with_mnemonic (fg_white_group, _("Black"));
  fg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (fg_black));
  gtk_widget_show (fg_black);
  gtk_container_add (GTK_CONTAINER (fg_color_menu), fg_black);

  bg_color = gtk_menu_item_new_with_mnemonic (_("Background Color"));
  gtk_widget_show (bg_color);
  gtk_container_add (GTK_CONTAINER (popup), bg_color);

  bg_color_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (bg_color), bg_color_menu);

  bg_white = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("White"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_white));
  gtk_widget_show (bg_white);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_white);

  bg_red = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Red"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_red));
  gtk_widget_show (bg_red);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_red);

  bg_green = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Green"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_green));
  gtk_widget_show (bg_green);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_green);

  bg_blue = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Blue"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_blue));
  gtk_widget_show (bg_blue);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_blue);

  bg_cyan = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Cyan"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_cyan));
  gtk_widget_show (bg_cyan);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_cyan);

  bg_magenta = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Magenta"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_magenta));
  gtk_widget_show (bg_magenta);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_magenta);

  bg_yellow = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Yellow"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_yellow));
  gtk_widget_show (bg_yellow);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_yellow);

  bg_black = gtk_radio_menu_item_new_with_mnemonic (bg_white_group, _("Black"));
  bg_white_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (bg_black));
  gtk_widget_show (bg_black);
  gtk_container_add (GTK_CONTAINER (bg_color_menu), bg_black);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (bg_black), TRUE);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (popup), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  exit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (popup), exit);

  g_signal_connect ((gpointer) basic, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_BASIC);
  g_signal_connect ((gpointer) grid, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_GRID);
  g_signal_connect ((gpointer) horizontal, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_HORIZONTAL);
  g_signal_connect ((gpointer) vertical, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_VERTICAL);
  g_signal_connect ((gpointer) blink, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_BLINK);
  g_signal_connect ((gpointer) text, "activate",
                    G_CALLBACK (on_mode_change),
                    MODE_TEXT);
  g_signal_connect ((gpointer) fg_white, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_WHITE);
  g_signal_connect ((gpointer) fg_red, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_RED);
  g_signal_connect ((gpointer) fg_green, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_GREEN);
  g_signal_connect ((gpointer) fg_blue, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_BLUE);
  g_signal_connect ((gpointer) fg_cyan, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_CYAN);
  g_signal_connect ((gpointer) fg_magenta, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_MAGENTA);
  g_signal_connect ((gpointer) fg_yellow, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_YELLOW);
  g_signal_connect ((gpointer) fg_black, "activate",
                    G_CALLBACK (on_color_change),
                    COLOR_BLACK);
  g_signal_connect ((gpointer) bg_white, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_WHITE);
  g_signal_connect ((gpointer) bg_red, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_RED);
  g_signal_connect ((gpointer) bg_green, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_GREEN);
  g_signal_connect ((gpointer) bg_blue, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_BLUE);
  g_signal_connect ((gpointer) bg_cyan, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_CYAN);
  g_signal_connect ((gpointer) bg_magenta, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_MAGENTA);
  g_signal_connect ((gpointer) bg_yellow, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_YELLOW);
  g_signal_connect ((gpointer) bg_black, "activate",
                    G_CALLBACK (on_bgcolor_change),
                    COLOR_BLACK);
  g_signal_connect ((gpointer) exit, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup, popup, "popup");
  GLADE_HOOKUP_OBJECT (popup, mode, "mode");
  GLADE_HOOKUP_OBJECT (popup, mode_menu, "mode_menu");
  GLADE_HOOKUP_OBJECT (popup, basic, "basic");
  GLADE_HOOKUP_OBJECT (popup, grid, "grid");
  GLADE_HOOKUP_OBJECT (popup, horizontal, "horizontal");
  GLADE_HOOKUP_OBJECT (popup, vertical, "vertical");
  GLADE_HOOKUP_OBJECT (popup, blink, "blink");
  GLADE_HOOKUP_OBJECT (popup, text, "text");
  GLADE_HOOKUP_OBJECT (popup, fg_color, "fg_color");
  GLADE_HOOKUP_OBJECT (popup, fg_color_menu, "fg_color_menu");
  GLADE_HOOKUP_OBJECT (popup, fg_white, "fg_white");
  GLADE_HOOKUP_OBJECT (popup, fg_red, "fg_red");
  GLADE_HOOKUP_OBJECT (popup, fg_green, "fg_green");
  GLADE_HOOKUP_OBJECT (popup, fg_blue, "fg_blue");
  GLADE_HOOKUP_OBJECT (popup, fg_cyan, "fg_cyan");
  GLADE_HOOKUP_OBJECT (popup, fg_magenta, "fg_magenta");
  GLADE_HOOKUP_OBJECT (popup, fg_yellow, "fg_yellow");
  GLADE_HOOKUP_OBJECT (popup, fg_black, "fg_black");
  GLADE_HOOKUP_OBJECT (popup, bg_color, "bg_color");
  GLADE_HOOKUP_OBJECT (popup, bg_color_menu, "bg_color_menu");
  GLADE_HOOKUP_OBJECT (popup, bg_white, "bg_white");
  GLADE_HOOKUP_OBJECT (popup, bg_red, "bg_red");
  GLADE_HOOKUP_OBJECT (popup, bg_green, "bg_green");
  GLADE_HOOKUP_OBJECT (popup, bg_blue, "bg_blue");
  GLADE_HOOKUP_OBJECT (popup, bg_cyan, "bg_cyan");
  GLADE_HOOKUP_OBJECT (popup, bg_magenta, "bg_magenta");
  GLADE_HOOKUP_OBJECT (popup, bg_yellow, "bg_yellow");
  GLADE_HOOKUP_OBJECT (popup, bg_black, "bg_black");
  GLADE_HOOKUP_OBJECT (popup, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (popup, exit, "exit");

  gtk_menu_set_accel_group (GTK_MENU (popup), accel_group);

  return popup;
}

