/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwin (void);
GtkWidget* create_popup (void);
GtkWidget* create_fg_color_selector (void);
GtkWidget* create_bg_color_selector (void);
